modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    modId="swl"
    version="0.2.1g-mixin-forge-1.20.1"
    displayName="SWL Mod"
    authors="__SK__"
    description='''This is SWL mod by __SK__'''

[[dependencies.swl]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.swl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.swl]]
    modId="tectonic"
    mandatory=false
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.swl]]
    modId="deeper_oceans"
    mandatory=false
    versionRange="[1.0.1a,)"
    ordering="AFTER"
    side="BOTH"